# 선문대학교 컴퓨터공학부
# 202243101 최완우
# Numpy & Pandas 연습

In [1]:
import numpy as np
my_array = np.array([1, 2, 3])

In [2]:
a = np.array([1, 2, 3])

a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [3]:
import numpy as np
sal = np.array([240, 260, 220, 255])

In [4]:
sal = sal + 100
print(sal)

[340 360 320 355]


In [5]:
scores = np.array([58, 72, 93, 94, 89, 78, 99])
scores[3:]

array([94, 89, 78, 99])

In [6]:
scores[4:-1]

array([89, 78])

In [7]:
np_array = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np_array[0, 2]

np.int64(3)

In [9]:
np_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8],
                     [9, 10, 11, 12], [13, 14, 15 ,16]])

np_array[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [10]:
ages = np.array([18, 19, 25, 30 ,28])
y = ages > 20
y

array([False, False,  True,  True,  True])

In [11]:
ages[ages > 20]

array([25, 30, 28])

In [13]:
import numpy as np
import pandas as pd
series = pd.Series([1, 1, np.nan, 4])
series

0    1.0
1    1.0
2    NaN
3    4.0
dtype: float64